// admin/template/template_vue3_startup/src/components/app/TopMenu.vue
<script setup lang="ts">
import { useAppSidebarMenuStore } from '@/stores/app-sidebar-menu';
import { useAppOptionStore } from '@/stores/app-option';
import { onMounted } from 'vue';
import { slideToggle } from '@/composables/slideToggle.js';
import { slideUp } from '@/composables/slideUp.js';
import { slideDown } from '@/composables/slideDown.js';
import TopMenuNav from '@/components/app/TopMenuNav.vue';

const appTopMenu = useAppSidebarMenuStore();
const appOption = useAppOptionStore();

function handleUnlimitedTopMenuRender() {
	"use strict";
	// function handle menu button action - next / prev
	function handleMenuButtonAction(element, direction) {
		var obj = element.closest('.menu');
		var objStyle = window.getComputedStyle(obj);
		var bodyStyle = window.getComputedStyle(document.querySelector('body'));
		var targetCss = (bodyStyle.getPropertyValue('direction') == 'rtl') ? 'margin-right' : 'margin-left';
		var marginLeft = parseInt(objStyle.getPropertyValue(targetCss));  
		var containerWidth = document.querySelector('.app-top-menu').clientWidth - document.querySelector('.app-top-menu').clientHeight * 2;
		var totalWidth = 0;
		var finalScrollWidth = 0;
		var controlPrevObj = obj.querySelector('.menu-control-start');
		var controlPrevWidth = (controlPrevObj) ? controlPrevObj.clientWidth : 0;
		var controlNextObj = obj.querySelector('.menu-control-end');
		var controlNextWidth = (controlPrevObj) ? controlNextObj.clientWidth : 0;
		var controlWidth = controlPrevWidth + controlNextWidth;
		
		var elms = [].slice.call(obj.querySelectorAll('.menu-item'));
		if (elms) {
			elms.map(function(elm) {
				if (!elm.classList.contains('.menu-control')) {
					totalWidth += elm.clientWidth;
				}
			});
		}

		switch (direction) {
			case 'next':
				var widthLeft = totalWidth + marginLeft - containerWidth;
				if (widthLeft <= containerWidth) {
					finalScrollWidth = widthLeft - marginLeft - controlWidth;
					setTimeout(function() {
						obj.querySelector('.menu-control.menu-control-end').classList.remove('show');
					}, 300);
				} else {
					finalScrollWidth = containerWidth - marginLeft - controlWidth;
				}

				if (finalScrollWidth !== 0) {
					obj.style.transitionProperty = 'height, margin, padding';
					obj.style.transitionDuration = '300ms';
					if (bodyStyle.getPropertyValue('direction') != 'rtl') {
						obj.style.marginLeft = '-' + finalScrollWidth + 'px';
					} else {
						obj.style.marginRight = '-' + finalScrollWidth + 'px';
					}
					setTimeout(function() {
						obj.style.transitionProperty = '';
						obj.style.transitionDuration = '';
						obj.querySelector('.menu-control.menu-control-start').classList.add('show');
					}, 300);
				}
				break;
			case 'prev':
				var widthLeft = -marginLeft;

				if (widthLeft <= containerWidth) {
					obj.querySelector('.menu-control.menu-control-start').classList.remove('show');
					finalScrollWidth = 0;
				} else {
					finalScrollWidth = widthLeft - containerWidth + controlWidth;
				}
				
				obj.style.transitionProperty = 'height, margin, padding';
				obj.style.transitionDuration = '300ms';
				
				if (bodyStyle.getPropertyValue('direction') != 'rtl') {
					obj.style.marginLeft = '-' + finalScrollWidth + 'px';
				} else {
					obj.style.marginRight = '-' + finalScrollWidth + 'px';
				}
				
				setTimeout(function() {
					obj.style.transitionProperty = '';
					obj.style.transitionDuration = '';
					obj.querySelector('.menu-control.menu-control-end').classList.add('show');
				}, 300);
				break;
		}
	}

	// handle page load active menu focus
	function handlePageLoadMenuFocus() {
		var targetMenu = document.querySelector('.app-top-menu .menu');
		if (!targetMenu) {
			return;
		}
		var targetMenuStyle = window.getComputedStyle(targetMenu);
		var bodyStyle = window.getComputedStyle(document.body);
		var targetCss = (bodyStyle.getPropertyValue('direction') == 'rtl') ? 'margin-right' : 'margin-left';
		var marginLeft = parseInt(targetMenuStyle.getPropertyValue(targetCss));
		var viewWidth = document.querySelector('.app-top-menu').clientWidth;
		var prevWidth = 0;
		var speed = 0;
		var fullWidth = 0;
		var controlPrevObj = targetMenu.querySelector('.menu-control-start');
		var controlPrevWidth = (controlPrevObj) ? controlPrevObj.clientWidth : 0;
		var controlNextObj = targetMenu.querySelector('.menu-control-end');
		var controlNextWidth = (controlPrevObj) ? controlNextObj.clientWidth : 0;
		var controlWidth = 0;

		var elms = [].slice.call(document.querySelectorAll('.app-top-menu .menu > .menu-item'));
		if (elms) {
			var found = false;
			elms.map(function(elm) {
				if (!elm.classList.contains('menu-control')) {
					fullWidth += elm.clientWidth;
					if (!found) {
						prevWidth += elm.clientWidth;
					}
					if (elm.classList.contains('active')) {
						found = true;
					}
				}
			});
		}
		
		var elm = targetMenu.querySelector('.menu-control.menu-control-end');
		if (prevWidth != fullWidth && fullWidth >= viewWidth) {
			elm.classList.add('show');
			controlWidth += controlNextWidth;
		} else {
			elm.classList.remove('show');
		}
		
		var elm = targetMenu.querySelector('.menu-control.menu-control-start');
		if (prevWidth >= viewWidth && fullWidth >= viewWidth) {
			elm.classList.add('show');
		} else {
			elm.classList.remove('show');
		}
		
		if (prevWidth >= viewWidth) {
			var finalScrollWidth = prevWidth - viewWidth + controlWidth;
			if (bodyStyle.getPropertyValue('direction') != 'rtl') {
				targetMenu.style.marginLeft = '-' + finalScrollWidth + 'px';
			} else {
				targetMenu.style.marginRight = '-' + finalScrollWidth + 'px';
			}
		}
	}

	// handle menu next button click action
	var elm = document.querySelector('[data-toggle="app-top-menu-next"]');
	if (elm) {
		elm.onclick = function(e) {
			e.preventDefault();
			handleMenuButtonAction(this,'next');
		};
	}
	
	// handle menu prev button click action
	var elm = document.querySelector('[data-toggle="app-top-menu-prev"]');
	if (elm) {
		elm.onclick = function(e) {
			e.preventDefault();
			handleMenuButtonAction(this,'prev');
		};
	}
	
	
	function enableFluidContainerDrag(containerClassName) {
		const container = document.querySelector(containerClassName);
		if (!container) {
			return;
		}
		const menu = container.querySelector('.menu');
		const menuItem = menu.querySelectorAll('.menu-item:not(.menu-control)');

		let startX, scrollLeft, mouseDown;
		let menuWidth = 0;
		let maxScroll = 0;

		menuItem.forEach((element) => {
			menuWidth += element.offsetWidth;
		});

		container.addEventListener('mousedown', (e) => {
			mouseDown = true;
			startX = e.pageX;
			scrollLeft = (menu.style.marginLeft) ? parseInt(menu.style.marginLeft) : 0;
			maxScroll = container.offsetWidth - menuWidth;
		});

		container.addEventListener('touchstart', (e) => {
			mouseDown = true;
			const touch = e.targetTouches[0];
			startX = touch.pageX;
			scrollLeft = (menu.style.marginLeft) ? parseInt(menu.style.marginLeft) : 0;
			maxScroll = container.offsetWidth - menuWidth;
		});

		container.addEventListener('mouseup', () => {
			mouseDown = false;
		});

		container.addEventListener('touchend', () => {
			mouseDown = false;
		});

		container.addEventListener('mousemove', (e) => {
			if (!startX || !mouseDown) return;
			if (window.innerWidth < 768) return;
			e.preventDefault();
			const x = e.pageX;
			const walkX = (x - startX) * 1;
			var totalMarginLeft = scrollLeft + walkX;
			if (totalMarginLeft <= maxScroll) {
				totalMarginLeft = maxScroll;
				menu.querySelector('.menu-control.menu-control-end').classList.remove('show');
			} else {
				menu.querySelector('.menu-control.menu-control-end').classList.add('show');
			}
			if (menuWidth < container.offsetWidth) {
				menu.querySelector('.menu-control.menu-control-start').classList.remove('show');
			}
			if (maxScroll > 0) {
				menu.querySelector('.menu-control.menu-control-end').classList.remove('show');
			}
			if (totalMarginLeft > 0) {
				totalMarginLeft = 0;
				menu.querySelector('.menu-control.menu-control-start').classList.remove('show');
			} else {
				menu.querySelector('.menu-control.menu-control-start').classList.add('show');
			}
			menu.style.marginLeft = totalMarginLeft + 'px';
		});

		container.addEventListener('touchmove', (e) => {
			if (!startX || !mouseDown) return;
			if (window.innerWidth < 768) return;
			e.preventDefault();
			const touch = e.targetTouches[0];
			const x = touch.pageX;
			const walkX = (x - startX) * 1;
			var totalMarginLeft = scrollLeft + walkX;
			if (totalMarginLeft <= maxScroll) {
				totalMarginLeft = maxScroll;
				menu.querySelector('.menu-control.menu-control-end').classList.remove('show');
			} else {
				menu.querySelector('.menu-control.menu-control-end').classList.add('show');
			}
			if (menuWidth < container.offsetWidth) {
				menu.querySelector('.menu-control.menu-control-start').classList.remove('show');
			}
			if (maxScroll > 0) {
				menu.querySelector('.menu-control.menu-control-end').classList.remove('show');
			}
			if (totalMarginLeft > 0) {
				totalMarginLeft = 0;
				menu.querySelector('.menu-control.menu-control-start').classList.remove('show');
			} else {
				menu.querySelector('.menu-control.menu-control-start').classList.add('show');
			}
			menu.style.marginLeft = totalMarginLeft + 'px';
		});
	}
	
	window.addEventListener('resize', function() {
		if (window.innerWidth >= 768) {
			var targetElm = document.querySelector('.app-top-menu');
			if (targetElm) {
				targetElm.removeAttribute('style');
			}
			var targetElm2 = document.querySelector('.app-top-menu .menu');
			if (targetElm2) {
				targetElm2.removeAttribute('style');
			}
			var targetElm3 = document.querySelectorAll('.app-top-menu .menu-submenu');
			if (targetElm3) {
				targetElm3.forEach((elm3) => {
					elm3.removeAttribute('style');
				});
			}
			handlePageLoadMenuFocus();
		}
		enableFluidContainerDrag('.app-top-menu');
	});
	
	if (window.innerWidth >= 768) {
		handlePageLoadMenuFocus();
		enableFluidContainerDrag('.app-top-menu');
	}
};

function handleTopMenuToggle(menus, forMobile = false) {
	menus.map(function(menu) {
		menu.onclick = function(e) {
			e.preventDefault();
			
			if (!forMobile || (forMobile && document.body.clientWidth < 768)) {
				var target = this.nextElementSibling;
				menus.map(function(m) {
					var otherTarget = m.nextElementSibling;
					if (otherTarget !== target) {
						slideUp(otherTarget);
						otherTarget.closest('.menu-item').classList.remove('expand');
						otherTarget.closest('.menu-item').classList.add('closed');
					}
				});
			
				slideToggle(target);
			}
		}
	});
};

function handleTopMenuSubMenu() {
	"use strict";
	
	var menuBaseSelector = '.app-top-menu .menu > .menu-item.has-sub';
	var submenuBaseSelector = ' > .menu-submenu > .menu-item.has-sub';
	
	// Menu - Toggle / Collapse
	var menuLinkSelector =  menuBaseSelector + ' > .menu-link';
	var menus = [].slice.call(document.querySelectorAll(menuLinkSelector));
	handleTopMenuToggle(menus, true);
	
	// Menu - Submenu lvl 1
	var submenuLvl1Selector = menuBaseSelector + submenuBaseSelector;
	var submenusLvl1 = [].slice.call(document.querySelectorAll(submenuLvl1Selector + ' > .menu-link'));
	handleTopMenuToggle(submenusLvl1);
	
	// Menu - Submenu lvl 2
	var submenuLvl2Selector = menuBaseSelector + submenuBaseSelector + submenuBaseSelector;
	var submenusLvl2 = [].slice.call(document.querySelectorAll(submenuLvl2Selector + ' > .menu-link'));
	handleTopMenuToggle(submenusLvl2);
};

onMounted(() => {
	handleUnlimitedTopMenuRender();
	handleTopMenuSubMenu();
});
</script>
<template>
	<div id="top-menu" class="app-top-menu" data-bs-theme="dark">
		<div class="menu">
			<template v-for="menu in appTopMenu">
				<top-menu-nav v-if="menu.title" v-bind:menu="menu"></top-menu-nav>
			</template>
			
			<div class="menu-item menu-control menu-control-start">
				<a href="javascript:;" class="menu-link" v-on:click="handleMenuButtonAction($event, 'prev')"><i class="fa fa-angle-left"></i></a>
			</div>
			<div class="menu-item menu-control menu-control-end">
				<a href="javascript:;" class="menu-link" v-on:click="handleMenuButtonAction($event, 'next')"><i class="fa fa-angle-right"></i></a>
			</div>
		</div>
	</div>
</template>

// admin/template/template_angularjs17/src/app/components/top-menu/top-menu.component.ts
import { Component, OnInit, AfterViewInit } 		 from '@angular/core';
import { AppMenuService } from '../../service/app-menus.service';
import { Router, ActivatedRoute, NavigationEnd } from '@angular/router';

declare var slideUp: any;
declare var slideToggle: any;

@Component({
  selector: 'top-menu',
  templateUrl: './top-menu.component.html'
})

export class TopMenuComponent implements OnInit {
  menus: any[] = [];
	
	constructor(private appMenuService: AppMenuService, private router: Router) { }
	
	ngOnInit() {
		this.menus = this.appMenuService.getAppMenus();
	}
	
	ngAfterViewInit() {
    setTimeout(() => {
			this.handleTopMenuSubMenu();
      
      window.addEventListener('resize', () => {
				if (window.innerWidth >= 768) {
					var targetElm = document.querySelector('.app-top-menu');
					if (targetElm) {
						targetElm.removeAttribute('style');
					}
					var targetElm2 = document.querySelector('.app-top-menu .menu');
					if (targetElm2) {
						targetElm2.removeAttribute('style');
					}
					var targetElm3 = document.querySelectorAll('.app-top-menu .menu-submenu');
					if (targetElm3) {
						targetElm3.forEach((elm3) => {
							elm3.removeAttribute('style');
						});
					}
					this.handleTopMenuMenuFocus();
				}
				this.handleTopMenuDrag('.app-top-menu');
			});
	
			if (window.innerWidth >= 768) {
				this.handleTopMenuMenuFocus();
				this.handleTopMenuDrag('.app-top-menu');
			}
    }, 50);
  }
	
	isActive(path: string) {
		return this.router.url === '/'+ path;
	}
	
	isChildActive(menus: any) {
		var active = false;
		if (menus.length > 0) {
			for (let menu of menus) {
				if (this.router.url === '/'+ menu.url) {
					active = true;
				}
			}
		}
		return active;
	}
	
	handleTopMenuMenuFocus() {
		const targetMenu = document.querySelector('.app-top-menu .menu') as HTMLElement | null;
		if (!targetMenu) {
			return;
		}
		const targetMenuStyle = window.getComputedStyle(targetMenu);
		const bodyStyle = window.getComputedStyle(document.body);
		const targetCss = bodyStyle.getPropertyValue('direction') === 'rtl' ? 'margin-right' : 'margin-left';
		const marginLeft = parseInt(targetMenuStyle.getPropertyValue(targetCss));
		const viewNav = document.querySelector('.app-top-menu') as HTMLElement | null;
		const viewWidth = viewNav ? viewNav.clientWidth : 0;
		let prevWidth = 0;
		let speed = 0;
		let fullWidth = 0;
		const controlPrevObj = targetMenu.querySelector('.menu-control-start') as HTMLElement | null;
		const controlPrevWidth = controlPrevObj ? controlPrevObj.clientWidth : 0;
		const controlNextObj = targetMenu.querySelector('.menu-control-end') as HTMLElement | null;
		const controlNextWidth = controlNextObj ? controlNextObj.clientWidth : 0;
		let controlWidth = 0;

		const elms = Array.from(document.querySelectorAll('.app-top-menu .menu > .menu-item')) as HTMLElement[];
		if (elms.length > 0) {
			let found = false;
			elms.forEach(function (elm) {
				if (!elm.classList.contains('menu-control')) {
					fullWidth += elm.clientWidth;
					if (!found) {
						prevWidth += elm.clientWidth;
					}
					if (elm.classList.contains('active')) {
						found = true;
					}
				}
			});
		}

		let elm = targetMenu.querySelector('.menu-control.menu-control-end') as HTMLElement | null;
		if (elm && prevWidth !== fullWidth && fullWidth >= viewWidth) {
			elm.classList.add('show');
			controlWidth += controlNextWidth;
		} else if (elm) {
			elm.classList.remove('show');
		}

		elm = targetMenu.querySelector('.menu-control.menu-control-start') as HTMLElement | null;
		if (elm && prevWidth >= viewWidth && fullWidth >= viewWidth) {
			elm.classList.add('show');
		} else if (elm) {
			elm.classList.remove('show');
		}

		if (prevWidth >= viewWidth) {
			const finalScrollWidth = prevWidth - viewWidth + controlWidth;
			if (bodyStyle.getPropertyValue('direction') !== 'rtl') {
				targetMenu.style.marginLeft = `-${finalScrollWidth}px`;
			} else {
				targetMenu.style.marginRight = `-${finalScrollWidth}px`;
			}
		}
	}
	
	handleTopMenuDrag(containerClassName: string) {
		const container = document.querySelector(containerClassName) as HTMLElement | null;
		if (!container) {
			return;
		}
		const menu = container.querySelector('.menu') as HTMLElement | null;
		const menuItem = menu ? Array.from(menu.querySelectorAll('.menu-item:not(.menu-control)')) as HTMLElement[] : [];

		let startX: number | null, scrollLeft: number, mouseDown: boolean;
		let menuWidth = 0;
		let maxScroll = 0;

		menuItem.forEach((element) => {
			menuWidth += element.offsetWidth;
		});

		container.addEventListener('mousedown', (e) => {
			mouseDown = true;
			startX = e.pageX;
			scrollLeft = parseInt(menu?.style.marginLeft || '0', 10);
			maxScroll = window.innerWidth - menuWidth;
		});

		container.addEventListener('touchstart', (e) => {
			mouseDown = true;
			const touch = e.targetTouches[0];
			startX = touch.pageX;
			scrollLeft = parseInt(menu?.style.marginLeft || '0', 10);
			maxScroll = window.innerWidth - menuWidth;
		});

		container.addEventListener('mouseup', () => {
			mouseDown = false;
		});

		container.addEventListener('touchend', () => {
			mouseDown = false;
		});

		container.addEventListener('mousemove', (e) => {
			if (!startX || !mouseDown || !menu) return;
			if (window.innerWidth < 768) return;
			e.preventDefault();
			const x = e.pageX;
			const walkX = (x - startX) * 1;
			let totalMarginLeft = scrollLeft + walkX;
			if (totalMarginLeft <= maxScroll) {
				totalMarginLeft = maxScroll;
				const menuControlEnd = menu.querySelector('.menu-control.menu-control-end') as HTMLElement | null;
				if (menuControlEnd) {
					menuControlEnd.classList.remove('show');
				}
			} else {
				const menuControlEnd = menu.querySelector('.menu-control.menu-control-end') as HTMLElement | null;
				if (menuControlEnd) {
					menuControlEnd.classList.add('show');
				}
			}
			if (menuWidth < window.innerWidth) {
				const menuControlStart = menu.querySelector('.menu-control.menu-control-start') as HTMLElement | null;
				if (menuControlStart) {
					menuControlStart.classList.remove('show');
				}
			}
			if (maxScroll > 0) {
				const menuControlEnd = menu.querySelector('.menu-control.menu-control-end') as HTMLElement | null;
				if (menuControlEnd) {
					menuControlEnd.classList.remove('show');
				}
			}
			if (totalMarginLeft > 0) {
				totalMarginLeft = 0;
				const menuControlStart = menu.querySelector('.menu-control.menu-control-start') as HTMLElement | null;
				if (menuControlStart) {
					menuControlStart.classList.remove('show');
				}
			} else {
				const menuControlStart = menu.querySelector('.menu-control.menu-control-start') as HTMLElement | null;
				if (menuControlStart) {
					menuControlStart.classList.add('show');
				}
			}
			menu.style.marginLeft = totalMarginLeft + 'px';
		});

		container.addEventListener('touchmove', (e) => {
			if (!startX || !mouseDown || !menu) return;
			if (window.innerWidth < 768) return;
			e.preventDefault();
			const touch = e.targetTouches[0];
			const x = touch.pageX;
			const walkX = (x - startX) * 1;
			let totalMarginLeft = scrollLeft + walkX;
			if (totalMarginLeft <= maxScroll) {
				totalMarginLeft = maxScroll;
				const menuControlEnd = menu.querySelector('.menu-control.menu-control-end') as HTMLElement | null;
				if (menuControlEnd) {
					menuControlEnd.classList.remove('show');
				}
			} else {
				const menuControlEnd = menu.querySelector('.menu-control.menu-control-end') as HTMLElement | null;
				if (menuControlEnd) {
					menuControlEnd.classList.add('show');
				}
			}
			if (menuWidth < window.innerWidth) {
				const menuControlStart = menu.querySelector('.menu-control.menu-control-start') as HTMLElement | null;
				if (menuControlStart) {
					menuControlStart.classList.remove('show');
				}
			}
			if (maxScroll > 0) {
				const menuControlEnd = menu.querySelector('.menu-control.menu-control-end') as HTMLElement | null;
				if (menuControlEnd) {
					menuControlEnd.classList.remove('show');
				}
			}
			if (totalMarginLeft > 0) {
				totalMarginLeft = 0;
				const menuControlStart = menu.querySelector('.menu-control.menu-control-start') as HTMLElement | null;
				if (menuControlStart) {
					menuControlStart.classList.remove('show');
				}
			} else {
				const menuControlStart = menu.querySelector('.menu-control.menu-control-start') as HTMLElement | null;
				if (menuControlStart) {
					menuControlStart.classList.add('show');
				}
			}
			menu.style.marginLeft = totalMarginLeft + 'px';
		});
	}
	
	handleTopMenuControlAction(event: MouseEvent, direction: string) {
		const element = event.currentTarget as HTMLElement;
		const obj = element.closest('.menu') as HTMLElement | null;
		if (!obj) {
			return;
		}

		const objStyle = window.getComputedStyle(obj);
		const bodyStyle = window.getComputedStyle(document.querySelector('body') as HTMLElement);
		const targetCss = bodyStyle.getPropertyValue('direction') == 'rtl' ? 'margin-right' : 'margin-left';
		const marginLeft = parseInt(objStyle.getPropertyValue(targetCss), 10);
		const containerWidth = (document.querySelector('.app-top-menu') as HTMLElement).clientWidth - (document.querySelector('.app-top-menu') as HTMLElement).clientHeight * 2;
		let totalWidth = 0;
		let finalScrollWidth = 0;
		const controlPrevObj = obj.querySelector('.menu-control-start') as HTMLElement | null;
		const controlPrevWidth = controlPrevObj?.clientWidth || 0;
		const controlNextObj = obj.querySelector('.menu-control-end') as HTMLElement | null;
		const controlNextWidth = controlPrevObj?.clientWidth || 0;
		const controlWidth = controlPrevWidth + controlNextWidth;

		const elms = Array.from(obj.querySelectorAll('.menu-item')) as HTMLElement[];
		if (elms) {
			elms.forEach((elm) => {
				if (!elm.classList.contains('.menu-control')) {
					totalWidth += elm.clientWidth;
				}
			});
		}

		switch (direction) {
			case 'next':
				const widthLeftNext = totalWidth + marginLeft - containerWidth;
				if (widthLeftNext <= containerWidth) {
					finalScrollWidth = widthLeftNext - marginLeft - controlWidth;
					setTimeout(() => {
						(obj.querySelector('.menu-control.menu-control-end') as HTMLElement)?.classList.remove('show');
					}, 300);
				} else {
					finalScrollWidth = containerWidth - marginLeft - controlWidth;
				}

				if (finalScrollWidth !== 0) {
					obj.style.transitionProperty = 'height, margin, padding';
					obj.style.transitionDuration = '300ms';
					if (bodyStyle.getPropertyValue('direction') != 'rtl') {
						obj.style.marginLeft = `-${finalScrollWidth}px`;
					} else {
						obj.style.marginRight = `-${finalScrollWidth}px`;
					}
					setTimeout(() => {
						obj.style.transitionProperty = '';
						obj.style.transitionDuration = '';
						(obj.querySelector('.menu-control.menu-control-start') as HTMLElement)?.classList.add('show');
					}, 300);
				}
				break;
			case 'prev':
				const widthLeftPrev = -marginLeft;

				if (widthLeftPrev <= containerWidth) {
					(obj.querySelector('.menu-control.menu-control-start') as HTMLElement)?.classList.remove('show');
					finalScrollWidth = 0;
				} else {
					finalScrollWidth = widthLeftPrev - containerWidth + controlWidth;
				}

				obj.style.transitionProperty = 'height, margin, padding';
				obj.style.transitionDuration = '300ms';

				if (bodyStyle.getPropertyValue('direction') != 'rtl') {
					obj.style.marginLeft = `-${finalScrollWidth}px`;
				} else {
					obj.style.marginRight = `-${finalScrollWidth}px`;
				}

				setTimeout(() => {
					obj.style.transitionProperty = '';
					obj.style.transitionDuration = '';
					(obj.querySelector('.menu-control.menu-control-end') as HTMLElement)?.classList.add('show');
				}, 300);
				break;
		}
	}
	
	handleTopMenuToggle(menus: HTMLElement[], forMobile = false) {
    menus.forEach((menu: HTMLElement) => {
      menu.onclick = (e: MouseEvent) => {
        e.preventDefault();

        if (!forMobile || (forMobile && document.body.clientWidth < 768)) {
          const target = menu.nextElementSibling as HTMLElement | null;
          menus.forEach((m: HTMLElement) => {
            const otherTarget = m.nextElementSibling as HTMLElement | null;
            if (otherTarget && otherTarget !== target) {
              slideUp(otherTarget);
              
              const otherTargetMenuItem = otherTarget.closest('.menu-item') as HTMLElement | null;
              if (otherTargetMenuItem) {
								otherTargetMenuItem.classList.remove('expand');
								otherTargetMenuItem.classList.add('closed');
              }
            }
          });
					if (target) {
          	slideToggle(target);
					}
        }
      };
    });
  }

  handleTopMenuSubMenu() {
    const menuBaseSelector = '.app-top-menu .menu > .menu-item.has-sub';
    const submenuBaseSelector = ' > .menu-submenu > .menu-item.has-sub';

    // Menu - Toggle / Collapse
    const menuLinkSelector = menuBaseSelector + ' > .menu-link';
    const menus = Array.from(document.querySelectorAll<HTMLElement>(menuLinkSelector));
    this.handleTopMenuToggle(menus, true);

    // Menu - Submenu lvl 1
    const submenuLvl1Selector = menuBaseSelector + submenuBaseSelector;
    const submenusLvl1 = Array.from(document.querySelectorAll<HTMLElement>(submenuLvl1Selector + ' > .menu-link'));
    this.handleTopMenuToggle(submenusLvl1);

    // Menu - Submenu lvl 2
    const submenuLvl2Selector = menuBaseSelector + submenuBaseSelector + submenuBaseSelector;
    const submenusLvl2 = Array.from(document.querySelectorAll<HTMLElement>(submenuLvl2Selector + ' > .menu-link'));
    this.handleTopMenuToggle(submenusLvl2);
  }
}
