// admin/template/template_react/src/pages/option/page-blank.js
import React from 'react';
import { Link } from 'react-router-dom';
import { Panel, PanelHeader, PanelBody } from './../../components/panel/panel.jsx';

function PageBlank() {
	return (
		<div>
			<ol className="breadcrumb float-xl-end">
				<li className="breadcrumb-item"><Link to="/page-option/blank">Home</Link></li>
				<li className="breadcrumb-item"><Link to="/page-option/blank">Page Options</Link></li>
				<li className="breadcrumb-item active">Blank Page</li>
			</ol>
			<h1 className="page-header">Blank Page <small>header small text goes here...</small></h1>
			<Panel>
				<PanelHeader>Panel Title here</PanelHeader>
				<PanelBody>
					Panel Content Here
				</PanelBody>
			</Panel>
		</div>
	)
}

export default PageBlank;

// admin/template/template_vue3/src/views/Page-blank.vue
<template>
	<div>
		<!-- BEGIN breadcrumb -->
		<ol class="breadcrumb float-xl-end">
			<li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
			<li class="breadcrumb-item"><a href="javascript:;">Page Options</a></li>
			<li class="breadcrumb-item active">Blank Page</li>
		</ol>
		<!-- END breadcrumb -->
		<!-- BEGIN page-header -->
		<h1 class="page-header">Blank Page <small>header small text goes here...</small></h1>
		<!-- END page-header -->
		<!-- BEGIN panel -->
		<panel>
			<panel-header>
				<panel-title>Panel Title here</panel-title>
				<panel-toolbar />
			</panel-header>
			<panel-body>
				Panel Content Here
			</panel-body>
		</panel>
		<!-- END panel -->
	</div>
</template>
