// admin/template/template_vue3/src/views/Page-with-fixed-footer.vue
<script>
import { useAppOptionStore } from '@/stores/app-option';
import highlightjs from '@/components/plugins/Highlightjs.vue';
import axios from 'axios';

const appOption = useAppOptionStore();

export default {
	data () {
		return {
			code1: ''
		}
	},
	components: {
		highlightjs: highlightjs
	},
	mounted() {
		appOption.appContentFullHeight = true;
		appOption.appContentClass = 'p-0';
		
		axios.get('/assets/data/page-option/with-fixed-footer.json').then((response) => {
			this.code1 = response.data;
		});
	},
	beforeRouteLeave (to, from, next) {
		appOption.appContentFullHeight = false;
		appOption.appContentClass = '';
		next();
	}
}
</script>
<template>
	<div class="d-flex flex-column h-100">
		<!-- BEGIN content-container -->
		<perfect-scrollbar class="app-content-padding flex-grow-1 overflow-hidden h-100">
			<!-- BEGIN breadcrumb -->
			<ol class="breadcrumb float-xl-end">
				<li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
				<li class="breadcrumb-item"><a href="javascript:;">Page Options</a></li>
				<li class="breadcrumb-item active">Page with Footer</li>
			</ol>
			<!-- END breadcrumb -->
			<!-- BEGIN page-header -->
			<h1 class="page-header">Page with Fixed Footer <small>header small text goes here...</small></h1>
			<!-- END page-header -->
		
			<!-- BEGIN panel -->
			<panel>
				<panel-header>
					<panel-title>Installation Settings</panel-title>
					<panel-toolbar />
				</panel-header>
				<panel-body>
					<p>
						Add the following app settings to the <code>page.vue</code> that you wish to change 
						<b>OR</b> change it from <code>/stores/app-option.ts</code> to make it affected to the whole app.
					</p>
				</panel-body>
				<!-- BEGIN hljs-wrapper -->
				<highlightjs :code="code1" />
			</panel>
			<!-- END panel -->
		</perfect-scrollbar>
		<!-- END content-container -->
			
			
		<!-- BEGIN #footer -->
		<div id="footer" class="app-footer m-0">
			&copy; 2023 Color Admin Responsive Admin Template - Sean Ngu All Rights Reserved
		</div>
		<!-- END #footer -->
	</div>
</template>

// admin/template/template_react/src/pages/option/page-with-fixed-footer.js
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Panel, PanelHeader, PanelBody } from './../../components/panel/panel.jsx';
import { AppSettings } from './../../config/app-settings.js';
import PerfectScrollbar from 'react-perfect-scrollbar';
import Highlight from 'react-highlight';

function PageWithFooter() {
  const context = React.useContext(AppSettings);
	const [code1, setCode1] = useState();

  useEffect(() => {
    context.handleSetAppContentFullHeight(true);
    context.handleSetAppContentClass('p-0 d-flex flex-column');

		fetch('/assets/data/page-with-fixed-footer/code-1.json').then(function(response) { return response.text(); }).then((html) => { setCode1(html); });
		
    return () => {
      context.handleSetAppContentFullHeight(false);
      context.handleSetAppContentClass('');
    };
		// eslint-disable-next-line
	}, []);

  return (
    <div className="h-100 d-flex flex-column">
      <PerfectScrollbar className="app-content-padding flex-grow-1 overflow-hidden" options={{ suppressScrollX: true }}>
        <ol className="breadcrumb float-xl-end">
          <li className="breadcrumb-item"><Link to="/page-option/with-fixed-footer">Home</Link></li>
          <li className="breadcrumb-item"><Link to="/page-option/with-fixed-footer">Page Options</Link></li>
          <li className="breadcrumb-item active">Page with Footer</li>
        </ol>
        <h1 className="page-header">Page with Fixed Footer <small>header small text goes here...</small></h1>
        <Panel>
          <PanelHeader>Installation Settings</PanelHeader>
          <PanelBody>
            <p>
              Add the following settings into your individual page or change the variable value from <code>app.jsx</code> to make it globally affected in your app.
            </p>
          </PanelBody>
          <div className="hljs-wrapper">
            <Highlight className='typescript'>{code1}</Highlight>
          </div>
        </Panel>
      </PerfectScrollbar>

      <div id="footer" className="app-footer m-0">
        &copy; 2023 Color Admin Responsive Admin Template - Sean Ngu All Rights Reserved
      </div>
    </div>
  );
}

export default PageWithFooter;
