// admin/template/template_vue3/src/views/Page-with-mega-menu.vue
<script>
import { useAppOptionStore } from '@/stores/app-option';
import highlightjs from '@/components/plugins/Highlightjs.vue';
import axios from 'axios';

const appOption = useAppOptionStore();

export default {
	data () {
		return {
			code1: ''
		}
	},
	components: {
		highlightjs: highlightjs
	},
	mounted() {
		appOption.appHeaderMegaMenu = true;
		
		axios.get('/assets/data/page-option/with-mega-menu.json').then((response) => {
			this.code1 = response.data;
		});
	},
	beforeRouteLeave (to, from, next) {
		appOption.appHeaderMegaMenu = false;
		next();
	}
}
</script>
<template>
	<div>
		<!-- BEGIN breadcrumb -->
		<ol class="breadcrumb float-xl-end">
			<li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
			<li class="breadcrumb-item"><a href="javascript:;">Page Options</a></li>
			<li class="breadcrumb-item active">Page with Mega Menu</li>
		</ol>
		<!-- END breadcrumb -->
		<!-- BEGIN page-header -->
		<h1 class="page-header">Page with Mega Menu <small>header small text goes here...</small></h1>
		<!-- END page-header -->
		
		<!-- BEGIN panel -->
		<panel>
			<panel-header>
				<panel-title>Installation Settings</panel-title>
				<panel-toolbar />
			</panel-header>
			<panel-body>
				<p>
					Add the following app settings to the <code>page.vue</code> that you wish to change 
					<b>OR</b> change it from <code>/stores/app-option.ts</code> to make it affected to the whole app.
				</p>
			</panel-body>
			<!-- BEGIN hljs-wrapper -->
			<highlightjs :code="code1" />
		</panel>
		<!-- END panel -->
	</div>
</template>

// admin/template/template_react/src/pages/option/page-with-mega-menu.js
import React, { useEffect, useContext, useState } from 'react';
import { Link } from 'react-router-dom';
import { Panel, PanelHeader, PanelBody } from './../../components/panel/panel.jsx';
import { AppSettings } from './../../config/app-settings.js';
import Highlight from 'react-highlight';

function PageWithMegaMenu() {
  const context = useContext(AppSettings);
	const [code1, setCode1] = useState();

  useEffect(() => {
    context.handleSetAppHeaderMegaMenu(true);
		
		fetch('/assets/data/page-with-mega-menu/code-1.json').then(function(response) { return response.text(); }).then((html) => { setCode1(html); });
		
    return () => {
      context.handleSetAppHeaderMegaMenu(false);
    };
		// eslint-disable-next-line
	}, []);

  return (
    <div>
      <ol className="breadcrumb float-xl-end">
        <li className="breadcrumb-item"><Link to="/page-option/with-mega-menu">Home</Link></li>
        <li className="breadcrumb-item"><Link to="/page-option/with-mega-menu">Page Options</Link></li>
        <li className="breadcrumb-item active">Page with Mega Menu</li>
      </ol>
      <h1 className="page-header">Page with Mega Menu <small>header small text goes here...</small></h1>
      <Panel>
        <PanelHeader>Installation Settings</PanelHeader>
        <PanelBody>
          <p>
            Add the following settings into your individual page or change the variable value from <code>app.jsx</code> to make it globally affected in your app.
          </p>
        </PanelBody>
        <div className="hljs-wrapper">
          <Highlight className='typescript'>{code1}</Highlight>
        </div>
      </Panel>
    </div>
  );
}

export default PageWithMegaMenu;
